In [2]:
import numpy as np

In [16]:
arr = np.arange(1, 101, 2)
arr.reshape(10, 5)


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [19]:
arr.shape

(50,)

In [20]:
arr.size

50

In [21]:
arr.itemsize

8

In [23]:
a = np.zeros(100)

In [25]:
a.reshape(10, 10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
b = np.linspace(1, 10, 90)
b

array([ 1.        ,  1.1011236 ,  1.20224719,  1.30337079,  1.40449438,
        1.50561798,  1.60674157,  1.70786517,  1.80898876,  1.91011236,
        2.01123596,  2.11235955,  2.21348315,  2.31460674,  2.41573034,
        2.51685393,  2.61797753,  2.71910112,  2.82022472,  2.92134831,
        3.02247191,  3.12359551,  3.2247191 ,  3.3258427 ,  3.42696629,
        3.52808989,  3.62921348,  3.73033708,  3.83146067,  3.93258427,
        4.03370787,  4.13483146,  4.23595506,  4.33707865,  4.43820225,
        4.53932584,  4.64044944,  4.74157303,  4.84269663,  4.94382022,
        5.04494382,  5.14606742,  5.24719101,  5.34831461,  5.4494382 ,
        5.5505618 ,  5.65168539,  5.75280899,  5.85393258,  5.95505618,
        6.05617978,  6.15730337,  6.25842697,  6.35955056,  6.46067416,
        6.56179775,  6.66292135,  6.76404494,  6.86516854,  6.96629213,
        7.06741573,  7.16853933,  7.26966292,  7.37078652,  7.47191011,
        7.57303371,  7.6741573 ,  7.7752809 ,  7.87640449,  7.97

In [34]:
c = np.random
c

<module 'numpy.random' from 'C:\\Users\\upm20\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\random\\__init__.py'>